### ISSUE TITLE
🐛 [BUG] - Can't parse string to bytes32 when getting gasEstimate

### ISSUE THREAD

**Issue by GrandinLuc** [vechain/vechain-sdk-js#1314]
### Description

I'm having this error with the SDK when trying to estimate gas fees for a transaction:
```
Method 'HttpClient.http()' failed.
    -Reason: 'Request failed with status 400 and message body: invalid length'
    -Parameters: 
        {
      "method": "POST",
      "url": "https://sync-mainnet.vechain.org/accounts/*"
    }

      104 |     };
      105 |
    > 106 |     const gasResult = await thorClient.gas.estimateGas(
          |                       ^
      107 |       transaction.clauses,
      108 |       transaction.simulateTransactionOptions.caller,
      109 |     );

      at HttpClient.http (../../node_modules/@vechain/sdk-network/dist/index.js:857:15)
      at TransactionsModule.simulateTransaction (../../node_modules/@vechain/sdk-network/dist/index.js:3304:12)
      at GasModule.estimateGas (../../node_modules/@vechain/sdk-network/dist/index.js:2784:25)
      at FeeDelegationService.updateWhitelist (src/common/fee-delegation/fee-delegation.service.ts:106:23)
      at Object.<anonymous> (test/integration/fee-delegation.spec.ts:36:5)
```

I tried to reproduce this here without success: https://docs.vechain.org/developer-resources/sdks-and-providers/sdk/thor-client#transactions
I'm using these versions:
"@vechain/sdk-core": "^1.0.0-beta.31",
"@vechain/sdk-network": "^1.0.0-beta.31",

### Reproduction steps

```bash
const abi = [
  {
    constant: false,
    inputs: [
      {
        name: '_address',
        type: 'address',
      },
      {
        name: 'tokenId',
        type: 'uint256',
      },
    ],
    name: 'addAllowedRecipientFor',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    constant: false,
    inputs: [
      {
        name: '_address',
        type: 'address',
      },
      {
        name: 'tokenId',
        type: 'uint256',
      },
    ],
    name: 'removeAllowedRecipientFor',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function'
  },
] as const;

const address = "0xf02f557c753edf5fcdcbfe4c1c3a448b3cc84d54"

const thorClient = ThorClient.fromUrl("https://sync-mainnet.vechain.org");
    const provider = new VeChainProvider(
      thorClient,
      new ProviderInternalBaseWallet([
        {
          privateKey: Buffer.from(
            '<private key string hex>',
            'hex',
          ),
          address: address,
        },
      ]),
      false,
    );

    const clause = clauseBuilder.functionInteraction(
      this.feeDelegationContractAddress,
      coder.createInterface(abi).getFunction(fn) as FunctionFragment,
      [address, 123],
    );
    const transaction = {
      clauses: [clause],
      simulateTransactionOptions: {
        caller: address,
      },
    };

    const gasResult = await thorClient.gas.estimateGas(
      transaction.clauses,
      transaction.simulateTransactionOptions.caller,
    );
```

### OS

Mac

**Comment by fabiorigam** [comment]
feeDelegationContractAddress was empty, causing the issue. Nothing wrong on SDK side.
