### ISSUE TITLE
Class extends valuu error

### ISSUE THREAD

**Issue by fabiorigam** [vechain/vechain-sdk-js#1506]
```
TypeError: Class extends value undefined is not a constructor or null

      3 | import { DEVICE_TYPE, TypedData, Wallet } from "~Model"
      4 | import { selectDevice, selectSelectedAccount, selectSelectedNetwork, useAppSelector } from "~Storage/Redux"
    > 5 | import { ThorClient, VeChainPrivateKeySigner, VeChainProvider } from "@vechain/sdk-network"
        | ^
      6 | import { HexUtils } from "~Utils"
      7 |
      8 | type Props = { typedData: TypedData }

      at Object.<anonymous> (node_modules/@vechain/sdk-network/dist/index.js:31:7265)
      at Object.<anonymous> (src/Hooks/useSignTypedData/useSignTypedData.ts:5:1)
      at Object.<anonymous> (src/Hooks/useSignTypedData/index.ts:1:1)
      at Object.<anonymous> (src/Hooks/index.ts:56:1)
      at Object.<anonymous> (src/Components/Providers/TranslationProvider.tsx:5:1)
      at Object.<anonymous> (src/Components/Providers/index.ts:1:1)
      at Object.<anonymous> (src/Components/index.ts:1:1)
      at Object.<anonymous> (src/Test/index.tsx:3:1)
      at Object.<anonymous> (src/Hooks/useSignMessage/useSignMessage.spec.ts:1:1)
```

**Comment by freemanzMrojo** [comment]
Checked this issue quickly (`veworld-mobile`), it is breaking here (`index.js`):

```
var Ue=class extends ethers.JsonRpcApiProvider
```

where `ethers` does not exist. I think it did not break locally because of the monorepo since we have `ethers` as part of `core` but not as part of `network`.

I think the solution is to add the dependency in `network`, will create a PR soon.

In case you wonder, for this issue https://github.com/vechain/vechain-sdk-js/issues/1467 it is working because what is being used is `index.mjs`.
