### ISSUE TITLE
🐛 [BUG] - UND_ERR_CONNECT_TIMEOUT

### ISSUE THREAD

**Issue by godlovericea** [vechain/vechain-sdk-js#1544]
### Description
[https://docs.vechain.org/developer-resources/sdks-and-providers/sdk/thor-client](url)

I readed the docs, but the TESTNET_URL  or  MAINNET_URL can not fetch 

methodName: 'HttpClient.http()',
errorMessage: 'fetch failed',
data: { method: 'GET', url: 'https://mainnet.vechain.org/blocks/best' },

methodName: 'HttpClient.http()',
errorMessage: 'fetch failed',
data: { method: 'GET', url: 'https://testnet.vechain.org/blocks/best' },

### Reproduction steps
```
const Test_Vet_NetWork = async () => {
    // const thorSoloClient = ThorClient.at(MAINNET_URL, {
    //     isPollingEnabled: false
    // });
    const httpClient = new SimpleHttpClient(TESTNET_URL);
    const thorSoloClient = new ThorClient(httpClient);
    try {
        const latestBlock = await thorSoloClient.blocks.getBestBlockCompressed();
        console.log(latestBlock);
    } catch (error) {
        console.error("Error fetching the latest block:", error);
    }
}

```

### Screenshots

[
![image](https://github.com/user-attachments/assets/602b90f0-9cfa-43aa-908f-acf3755de28b)
](url)
```bash
![DESCRIPTION](LINK.png)
```

**Comment by godlovericea** [comment]
![image](https://github.com/user-attachments/assets/ccea4345-1d40-4ca8-9567-f075cff9b4cb)

**Comment by freemanzMrojo** [comment]
Hi @godlovericea,

We haven't come across an error like this in our test suite for  the `mainnet` ones, could you check if this error described here makes sense to you (related to the Node version)? https://github.com/nodejs/undici/issues/1531

Thanks in advance!

**Comment by Behnoudmst** [comment]
I am getting this error on nextjs + Vercel + node 12, any workarounds ? 
```
TypeError: fetch failed
    at /opt/rust/undici-runtime.js:41:5170 {
  [cause]: Error: write ETIMEDOUT
```

**Comment by lucanicoladebiasi** [comment]
Please, can you tell me the version of Next.js you are using?

**Comment by lucanicoladebiasi** [comment]
Please Behnoudmst, can you tell me the version of Next.JS you are using?

> I am getting this error on nextjs + Vercel + node 20, any workarounds ?
> 
> ```
> TypeError: fetch failed
>     at /opt/rust/undici-runtime.js:41:5170 {
>   [cause]: Error: write ETIMEDOUT
> ```

**Comment by lucanicoladebiasi** [comment]
The **fetch** API are common in browsers and in **Node.JS** from version > v18.20.6.
When you use **Next.js or execute the code in a test environment (e.g., using Jest), it runs in the **Node.js** runtime by default, but - depending the runtime settings - **Next.JS** loses the reference to both **fetch** provided **Node.JS** >- v18 and **fetch** provided by the most common browsers.

Since **Node.js 20** includes **fetch API**, you should not be required to install [node-fetch](https://www.npmjs.com/package/node-fetch) Polyfill library.

In recent versions of **Next.js** >- 13, **fetch** is [made available on the server side](https://nextjs.org/blog/next-13#built-in-fetch-request). However, it still doesn't work in a **Node.js** test environment unless you mock or define it explicitly.

**Comment by Behnoudmst** [comment]
> Please Behnoudmst, can you tell me the version of Next.JS you are using?
> It is also important you tell me if this problem happens when run Next.JS or when Jest test library runs the code. 
> 
> > I am getting this error on nextjs + Vercel + node 20, any workarounds ?
> > 
> > ```
> > TypeError: fetch failed
> >     at /opt/rust/undici-runtime.js:41:5170 {
> >   [cause]: Error: write ETIMEDOUT
> > ```
> 
> 

I am using next v14.2.23 on production. I get random errors when I try to fetch data from my backend on GCP. Its a server rendered page. I tried with node 20 but the issue still there.

**Comment by lucanicoladebiasi** [comment]
I don't think the problem is related with **Node.JS** itself, I think it is because moving through the runtime stack from **Next** to the the Rust JS processor **undici** the `fetch` API is lost. I'm going to check if **undici** supports the **fetch** API and how, because this cold be an issue.

**Comment by lucanicoladebiasi** [comment]
Yes, `fetch` is provided by [undici](https://github.com/nodejs/undici) but please, note at https://github.com/nodejs/undici?tab=readme-ov-file#undicifetchinput-init-promise it has the same functionalities but a different internal representation and it must be imported with 
```javascript
import { fetch } from 'undici'
```

Investigation continues...

**Comment by lucanicoladebiasi** [comment]
## Diagnosis

Multiple sources confirm problems about how **Vercel** deploys **NEXT.JS** in its cloud infrastructure bridging **fetch** API with **undici** library to implement HTTP calls.

The solution of the problem is not in the scope of **VeChain** possibilities.

## References

The [**undici**](https://undici.nodejs.org/) library provides [**fetch**](https://undici.nodejs.org/#/?id=undicifetchinput-init-promise) implementation compatible with
**MDN** [**fetch**](https://developer.mozilla.org/en-US/docs/Web/API/Window/fetch).

[**NEXT.JS**](https://nextjs.org/) promotes the use of **undici** because more efficient and way faster, see
**Medium** - [HTTP Fundamentals: Understanding Undici and its Working Mechanism(https://blog.platformatic.dev/http-fundamentals-understanding-undici-and-its-working-mechanism).

**NEXT.JS** has a node polyfill for fetch, which uses either **undici** or **node-fetch** depending on an environment variable called `__NEXT_USE_UNDICI`.

Unfortunately many sources report **NEXT.JS** deployed via [**Vercel**](https://vercel.com/)
shows bugs bridging **fetch** API on **undici** implementations. See
- **Vercel** - [BUG: Vercel is somehow overwriting fetch from undici with a non-spec compliant implementation](https://github.com/vercel/vercel/issues/9690);
- **Vercel** - [Using Undici as node fetch polyfill causes fetch failed](https://github.com/vercel/next.js/issues/48744);
- **Medium** - [Fix: Vercel + Next.JS “fetch failed” from undici polyfill(https://medium.com/@kaloyan_17221/fix-vercel-next-js-fetch-failed-from-undici-polyfill-8c66346c9c2f).

## Investigation

The *Reproduction steps* for this bug don't tell if the bug manifests itself in a *client* or *server* code.
Imaging the problem occours for *client* code as typical use case for **NEXT.JS** deployment, we wrote
the following `page.tsx` code to deploy in **Vercel** and try to reproduce the bug.
The code uses **fetch** to call **VeChain** [testnet](https://testnet.vechain.org).

```typescript
'use client';

import React, {useState} from "react";

export default function Page() {
    const url = 'https://testnet.vechain.org/blocks/best';
    const [count, setCount] = useState(0);
    const [json, setJson] = useState<string>('unknown');

    const fetchLastBlock = async (): Promise<void> => {
        setCount(count + 1);
        console.log(`Button clicked ${count} times!`);

        const options = {method: 'GET', headers: {Accept: 'application/json, text/plain'}};

        try {
            const response = await fetch(url, options);
            const data = await response.json();
            const json = JSON.stringify(data, null, 2);
            setJson(json);
            console.log(json);
        } catch (error) {
            console.error(error);
        }
    };

    return (
        <div className="p-4">
            <h1 className="text-2xl font-bold">BUG 1455</h1>
            <button
                className="mt-4 px-4 py-2 bg-blue-500 text-white rounded hover:bg-blue-600"
                onClick={() => {
                    void (async () => {
                        await fetchLastBlock();
                    })();
                }}
            >
                Click me to test
            </button>
            <p className="mt-2 text-lg">You clicked the button {count} times.</p>
            <div>
                <hr/>
            </div>
            <div>
                <pre>
                    BLOCK: {json}
                </pre>
            </div>
        </div>
    );
}
```

For completeness, the `package.json` is shown below.

```json
{
  "name": "bug1544_1",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev --turbopack",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "next": "15.1.7",
    "react": "^19.0.0",
    "react-dom": "^19.0.0"
  },
  "devDependencies": {
    "@eslint/eslintrc": "^3",
    "@types/node": "^20",
    "@types/react": "^19",
    "@types/react-dom": "^19",
    "eslint": "^9",
    "eslint-config-next": "15.1.7",
    "postcss": "^8",
    "tailwindcss": "^3.4.1",
    "typescript": "^5"
  }
}
```

The code is deployed on **Vercel** with "Settings -> Environment Variables" set as `__NEXT_USE_UNDICI = true`.

![Image](https://github.com/user-attachments/assets/6df66365-f70c-4cdc-8733-c02dda62e8d4)

**Vercel** deploys with **NEXT.JS** version **15.1.7**, hence this version differs from the version **14.2.20**
reported for this bug case; nevertheless the same **Node.JS** version **20.x** was used for the investigation,
see the attached picture from **Vercel** "Settings -> Build and Deployment".

![Image](https://github.com/user-attachments/assets/3627902b-0380-4ae7-9aa3-5a3108f968f8)

**Comment by victhorbi** [comment]
I consider this ticket closed.
Please, reopen if you face the same issue again.
